name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Construir projeto Angular
        run: npm run build -- --output-path=dist --base-href /AndreSantos_Portfolio/

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
